### ISSUE TITLE
Error "TypeError: Cannot set property 'email' of undefined"

### ISSUE THREAD

**Issue by mhajder** [benkaiser/facebook-chat-downloader#2]
```
TypeError: Cannot set property 'email' of undefined
    at router.post (c:\facebook-chat-downloader\controllers\index.js:25:21)
    at Layer.handle [as handle_request] (c:\facebook-chat-downloader\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\facebook-chat-downloader\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\facebook-chat-downloader\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\facebook-chat-downloader\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:174:3)
    at router (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (c:\facebook-chat-downloader\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:317:13)
    at c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:284:7
    at next (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:275:10)
    at session (c:\facebook-chat-downloader\node_modules\express-session\index.js:189:7)
    at Layer.handle [as handle_request] (c:\facebook-chat-downloader\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:317:13)
    at c:\facebook-chat-downloader\node_modules\express\lib\router\index.js:284:7
```

**Comment by benkaiser** [comment]
This repository isn't really actively used by me or maintained, PRs are welcome

**Comment by mhajder** [comment]
Ok, but I have one question where I should change the Redis port?

Here?
https://github.com/benkaiser/facebook-chat-downloader/blob/0d48081d92d5b2cd2ebbb125e80998556d2c003b/index.js#L20

**Comment by benkaiser** [comment]
Are you using bin/go or running it outside of docker?

If it's outside of docker

REDIS_URL=https://localhost:1234/ npm start
